/*****************************************************************************/
/* 		"game.c"      														 */
/* Disclaimer:															     */
/* Author: Carlos L Sanchez Vila                                             */
/* INSTRUCTIONS/HOW TO USE:													 */
/* To compile:            													 */
/* Navigate to the folder that contains the program files and enter or copy	 */
/* copy and paste the following line in a terminal window:					 */	
/* Option 1	Compile using gcc:												 */	
/* 		gcc game.c deck.c player.c 											 */
/* Option 2 build the program using the included make file:					 */	
/*      enter:  														     */
/* 			   "make" or "make build" in a terminal window to compile and 	 */
/*				generate the game files 								     */
/* To execute:																 */
/* After compiling and generateing the executable file following either one  */
/* the two options above, the progarm can be executed and run by entering	 */
/* "./cardGame.out" in the terminal											 */
/* For better performance plese resize your terminal or console window 		 */
/* to around 800 x 800 pixes to be able to view the game as it was intended	 */
/* by the developer															 */
/*****************************************************************************/

#include "game.h" 					/* Including the main header file*/

/**
 * main: The following program contains the functions to recreate a card game
 * which consists of a traditional deck of 52 cards. The program contains 
 * several functions that allow to create a deck, shuffle it, add new players
 * and assign each one of them cards. The number of players and the length of 
 * each hand of cards will be entered when executing the program through the 
 * command line. Notice that these inputs should not execeed their defined 
 * possible maximun number. And that the nuber of arguments entered throught 
 * the command line should be always 3, the program name, the length of the 
 * hand and the number of players/hands that will be generated by the game.
 * 
 * @param  argc: This parameter  represents the number of arguments entered 
 * through the command line.
 * 
 * @param  argv: This paramenter is an array containing all of the arguments 
 * entered through the command line, including the program name.
 * @return: Returns zero if there are no program errors.
 */
int main(int argc, char *argv[])
{	

	/* Execute the game only if imput is validated, ignore otherwise */
	if(validateCommandLineInput(argc, argv) 
		&& (validateGameInput(atoi(argv[1]), atoi(argv[2]))))
	{	
		/* Get the validated arguments. */
		int handLength = atoi(argv[1]);
		int numHands = atoi(argv[2]);

		/* Declare the two arrays that the game will use, deck and players.*/
		 Card deck[CARDS_IN_A_DECK];
		 Player playersInGame[numHands];
		
		/* Call the diferent methods that will simulate the game.*/
		/* Create the deck and show it to the user.*/
		createDeck(&deck[0]);
		printf("%s\n","Printing the new Deck:");
		displayDeckInLines(&deck[0]);

		/* Shuffle the deck and show it to the user.*/
		shuffleDeck(deck);
		printf("%s\n","Printing the recently shuffled Deck:");
		displayDeckInLines(&deck[0]);

		/* Initialize the players and print their hands. */
		createAllPlayers(playersInGame, handLength, numHands);
		dealDeck(deck, playersInGame, handLength, numHands);
		displayAllPlayersHands(playersInGame, handLength, numHands);

		printf("%s\n", "********> Evaluated Hands <**********");
		/* Evaluate Player Hands and Print.*/
		printf("%s\n\n","Printing the evaluated player hands:");
		evaluateHand(playersInGame, handLength, numHands);

	}	

	return NO_PROGRAM_ERRORS;
}

/**
 * validateCommandLineInput: This function checks the input entered through 
 * the command line, the verification in this method is a two step process,
 * first it checks that the number of arguments entered is 3, that is: two 
 * numbers and the program name, if the number of arguments is any other than 
 * 3 the function returns FALSE. The seconds step which begins if the number
 * of arguments entered is correct (equal to 3) checks if the arguments are 
 * numbers, if any of the two arguments is a string the function will take any 
 * readable number from the  string by accepting the longest prefixing number 
 * in the string and return TRUE and returning FALSE there isn't readable 
 * numbers.
 * 
 * @param  argc: This parameter indicates the number of arguments entered 
 * through the command line, counting one for the program name and any other 
 * argument entered after it.
 * 
 * @param  argsPointer: This parameter is an array containing all of the 
 * parameters entered through the command line starting at possition 0 where 
 * the program name is contained and continuing on with any other entered 
 * parameter at possition 2 to N where N is the number of arguments (argc) 
 * minus one.
 * 
 * @return:	The program returns TRUE if the input is validated, and FALSE if 
 * the input isn't.
 */
bool validateCommandLineInput(int argc, char *argsPointer[]){

	if(argc != NUM_ALLOWED_ARGS){
		printf("%s\n","ERROR! Please enter the right amount of arguments." );
		return FALSE;
	}else {
		int cardsHand = atoi(argsPointer[1]);
		int numHands = atoi(argsPointer[2]);

		if((cardsHand == 0) || (numHands == 0)){
			printf("%s\n","ERROR! Invalid entry, please enter two numbers.");
			return FALSE;
		}
		else{
			return TRUE;
		}
	}
}



















